name: .NET TestProject1 CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Check out your code

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore TestProject1/TestProject1.csproj

    - name: Build
      run: dotnet build TestProject1/TestProject1.csproj --no-restore

    - name: Test
      run: dotnet test TestProject1/TestProject1.csproj --no-build --verbosity normal
